import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const copyFilesPlugin = {
	name: "copy-files",
	setup(build) {
		build.onEnd(() => {
			try {
				if (!fs.existsSync("dist")) {
					fs.mkdirSync("dist", { recursive: true });
				}
				fs.copyFileSync("manifest.json", "dist/manifest.json");
				if (fs.existsSync("styles.css")) {
					fs.copyFileSync("styles.css", "dist/styles.css");
				}
				console.log("Copied manifest.json and styles.css to dist/");

				const mainJsPath = "dist/main.js";
				if (fs.existsSync(mainJsPath)) {
					let content = fs.readFileSync(mainJsPath, "utf8");
					content = content.replace("all[name]", "Reflect.get(all, name)");
					content = content.replace("from[key]", "Reflect.get(from, key)");
					fs.writeFileSync(mainJsPath, content, "utf8");
					console.log("Post-processed dist/main.js to remove helper bracket notation.");
				}
			} catch (err) {
				console.error("Failed to copy files to dist/:", err);
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	plugins: [copyFilesPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
