import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Ensure dist/ directory exists
if (!fs.existsSync("dist")) {
	fs.mkdirSync("dist");
}

const copyFiles = () => {
	try {
		fs.copyFileSync("manifest.json", "dist/manifest.json");
		if (fs.existsSync("styles.css")) {
			fs.copyFileSync("styles.css", "dist/styles.css");
		}
	} catch (e) {
		console.error("Failed to copy manifest.json / styles.css to dist/", e);
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
});

copyFiles();

if (prod) {
	await context.rebuild();
	copyFiles();
	process.exit(0);
} else {
	await context.watch();
}
