/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var P = Object.create;
var f = Object.defineProperty;
var M = Object.getOwnPropertyDescriptor;
var O = Object.getOwnPropertyNames;
var T = Object.getPrototypeOf,
    _ = Object.prototype.hasOwnProperty;
var D = (r, e) => {
    for (var t in e) f(r, t, { get: e[t], enumerable: !0 })
},
W = (r, e, t, n) => {
    if (e && typeof e == "object" || typeof e == "function")
        for (let i of O(e)) !_.call(r, i) && i !== t && f(r, i, { get: () => e[i], enumerable: !(n = M(e, i)) || n.enumerable });
    return r
};
var I = (r, e, t) => (t = r != null ? P(T(r)) : {}, W(e || !r || !r.__esModule ? f(t, "default", { value: r, enumerable: !0 }) : t, r)),
    K = r => W(f({}, "__esModule", { value: !0 }), r);
var N = {};
D(N, { default: () => b });
module.exports = K(N);
var S = require("obsidian");

var L = {
    language: "en",
    defaultAction: "follow-setting",
    modifierAction: "toggle-default",
    shiftAction: "new-tab",
    splitDirection: "vertical",
    focusPane: !0,
    fallbackToBrowserWhenWebViewerUnavailable: !0,
    detectionFallback: "browser",
    debugLog: !1
};

var TRANSLATIONS = {
    en: {
        title: "Split Web Viewer Modifier",
        intro: "Configure open actions for normal clicks, Shift clicks, and Cmd/Ctrl clicks. The options are unified and can be freely combined.",
        langSettingName: "Language",
        langSettingDesc: "Choose the display language for the plugin settings.",
        clickNormalName: "Normal click behavior",
        clickNormalDesc: "How external links open when clicked normally (without modifier keys). You can follow Web Viewer settings or explicitly specify an action.",
        followSettingOption: "Follow Web Viewer's external link setting",
        clickShiftName: "Shift click behavior",
        clickShiftDesc: "How external links open when holding Shift. 'Open new Web Viewer tab' is recommended.",
        clickCmdCtrlName: "Cmd/Ctrl click behavior",
        clickCmdCtrlDesc: "How external links open when holding Cmd/Ctrl. 'Toggle default target' is recommended (Web Viewer <-> Browser).",
        toggleDefaultOption: "Toggle default target (Web Viewer ↔ Browser)",
        disabledOption: "Disabled (Follow normal click)",
        splitDirectionName: "Split direction",
        splitDirectionDesc: "Where to split. 'vertical' splits to the right, 'horizontal' splits below. Only applies when a new split pane is created.",
        splitVertical: "vertical (Split right)",
        splitHorizontal: "horizontal (Split bottom)",
        focusPaneName: "Focus new split after opening",
        focusPaneDesc: "When enabled, automatically focuses the Web Viewer pane after opening a link.",
        fallbackName: "Fallback to browser when Web Viewer is unavailable",
        fallbackDesc: "When Web Viewer core plugin is disabled or fails, automatically open the link in the default web browser.",
        detectionFallbackName: "Fallback behavior when auto-detection fails",
        detectionFallbackDesc: "Only used when 'Normal click behavior' is set to 'Follow Web Viewer's external link setting' and the plugin fails to detect the Web Viewer's internal toggle status.",
        detectBrowserOption: "Treat as 'Web Viewer external link disabled' (Use default browser)",
        detectWebViewOption: "Treat as 'Web Viewer external link enabled' (Use Web Viewer)",
        debugLogName: "Debug log",
        debugLogDesc: "Print intercept logs to the Developer Tools Console. Helpful for troubleshooting link opening issues.",
        tipText: "Tip: If you turn off the Web Viewer's 'Open external links' option, and set 'Cmd/Ctrl click behavior' here to 'Toggle default target', then Cmd/Ctrl + click will open links inside the Web Viewer.",
        noticeNoWebViewer: "Web Viewer core plugin not detected.",
        noticeFallbackBrowser: "Falling back to opening in default browser.",
        noticeEnableFirst: "Please enable it in Core plugins first.",
        noticeFailWebViewer: "Failed to open in Web Viewer. Fell back to default browser.",
        noticeFailWebViewerConsole: "Failed to open in Web Viewer. Check Developer Tools console for error details.",
        noticeFailBrowser: "Failed to open default browser. Please check your system default browser settings.",
        reuse: "Reuse current Web Viewer tab (navigates in-place)",
        "new-tab": "Open new Web Viewer tab (no split)",
        "new-split": "Open in a new split Web Viewer pane",
        browser: "Open in default browser"
    },
    zh: {
        title: "Split Web Viewer Modifier",
        intro: "为普通点击、Shift 点击、Cmd/Ctrl 点击分别配置打开方式。选项集统一，自由组合。",
        langSettingName: "语言 (Language)",
        langSettingDesc: "选择插件设置的显示语言。",
        clickNormalName: "普通点击行为",
        clickNormalDesc: "无修饰键直接点击外链时的打开方式。可以选择跟随 Web Viewer 的外链设置，也可以直接指定一种方式。",
        followSettingOption: "跟随 Web Viewer 的外链设置",
        clickShiftName: "Shift 点击行为",
        clickShiftDesc: "按住 Shift 点击时使用的打开方式。推荐“新开 Web Viewer tab”。",
        clickCmdCtrlName: "Cmd/Ctrl 点击行为",
        clickCmdCtrlDesc: "按住 Cmd（macOS）或 Ctrl（Windows/Linux）点击时的打开方式。推荐“反转默认目标”：默认进 Web Viewer 时就进浏览器，反之亦然。",
        toggleDefaultOption: "反转默认目标（Web Viewer ↔ 浏览器）",
        disabledOption: "不拦截（跟随普通点击）",
        splitDirectionName: "分屏方向",
        splitDirectionDesc: "vertical 会在当前 pane 右侧拆分，horizontal 会在下方拆分。仅在需要新建分屏时生效。",
        splitVertical: "vertical（右侧分屏）",
        splitHorizontal: "horizontal（下方分屏）",
        focusPaneName: "打开后聚焦新分屏",
        focusPaneDesc: "开启后，网页打开方式会自动切换到 Web Viewer pane。",
        fallbackName: "无法使用 Web Viewer 时回退到浏览器",
        fallbackDesc: "当 Web Viewer 未启用或打开失败时，自动用系统默认浏览器打开。",
        detectionFallbackName: "自动检测失败时的回退行为",
        detectionFallbackDesc: "仅在你把“普通点击行为”设为“跟随 Web Viewer 的外链设置”，且插件没能识别 Web Viewer 内部开关时生效。",
        detectBrowserOption: "按“未开启外链 Web Viewer”处理（走默认浏览器）",
        detectWebViewOption: "按“已开启外链 Web Viewer”处理（走 Web Viewer）",
        debugLogName: "调试日志",
        debugLogDesc: "开启后在开发者工具 Console 打印拦截日志，排查链接没走 Web Viewer 时很有用。",
        tipText: "提示：如果你把 Web Viewer 的“打开外部链接”关掉，并且这里的 Cmd/Ctrl 点击行为设为“反转默认目标”，那 Cmd/Ctrl + 点击就会在 Web Viewer 中打开。",
        noticeNoWebViewer: "未检测到已启用的 Web Viewer 核心插件。",
        noticeFallbackBrowser: "已改为用默认浏览器打开。",
        noticeEnableFirst: "请先在 Core plugins 中启用它。",
        noticeFailWebViewer: "在 Web Viewer 中打开失败，已回退到默认浏览器。",
        noticeFailWebViewerConsole: "在 Web Viewer 中打开失败，请打开开发者工具查看错误。",
        noticeFailBrowser: "打开默认浏览器失败，请检查系统默认浏览器设置。",
        reuse: "复用当前 Web Viewer（在原 pane 换 URL）",
        "new-tab": "新开 Web Viewer tab（不复用，不分屏）",
        "new-split": "新建分屏 Web Viewer",
        browser: "在默认浏览器打开"
    },
    ru: {
        title: "Split Web Viewer Modifier",
        intro: "Настройте действия при открытии для обычных кликов, кликов с Shift и кликов с Cmd/Ctrl. Параметры унифицированы и могут свободно комбинироваться.",
        langSettingName: "Язык (Language)",
        langSettingDesc: "Выберите язык отображения для настроек плагина.",
        clickNormalName: "Обычный клик",
        clickNormalDesc: "Как открываются внешние ссылки при обычном клике (без модификаторов). Вы можете следовать настройкам Web Viewer или явно указать действие.",
        followSettingOption: "Следовать настройкам внешних ссылок Web Viewer",
        clickShiftName: "Клик с Shift",
        clickShiftDesc: "Как открываются внешние ссылки при удержании Shift. Рекомендуется 'Открыть в новой вкладке Web Viewer'.",
        clickCmdCtrlName: "Клик с Cmd/Ctrl",
        clickCmdCtrlDesc: "Как открываются внешние ссылки при удержании Cmd/Ctrl. Рекомендуется 'Переключить целевое назначение по умолчанию' (Web Viewer <-> Браузер).",
        toggleDefaultOption: "Переключить цель по умолчанию (Web Viewer ↔ Браузер)",
        disabledOption: "Отключено (Следовать обычному клику)",
        splitDirectionName: "Направление разделения",
        splitDirectionDesc: "Где разделять. 'vertical' разделяет справа, 'horizontal' разделяет снизу. Применяется только при создании новой панели разделения.",
        splitVertical: "вертикально (Разделить справа)",
        splitHorizontal: "горизонтально (Разделить снизу)",
        focusPaneName: "Фокусировать новое разделение после открытия",
        focusPaneDesc: "Если включено, автоматически переключает фокус на панель Web Viewer после открытия ссылки.",
        fallbackName: "Возврат к браузеру, если Web Viewer недоступен",
        fallbackDesc: "Если плагин Web Viewer отключен или не работает, автоматически открывать ссылку в браузере по умолчанию.",
        detectionFallbackName: "Действие по умолчанию при сбое автоопределения",
        detectionFallbackDesc: "Используется только когда для 'Обычного клика' выбрано 'Следовать настройкам внешних ссылок Web Viewer' и плагин не может определить статус переключателя Web Viewer.",
        detectBrowserOption: "Считать внешние ссылки Web Viewer отключенными (Браузер по умолчанию)",
        detectWebViewOption: "Считать внешние ссылки Web Viewer включенными (Использовать Web Viewer)",
        debugLogName: "Журнал отладки",
        debugLogDesc: "Выводить логи перехвата в консоль инструментов разработчика. Полезно для поиска проблем с открытием ссылок.",
        tipText: "Совет: Если вы отключите параметр 'Открыть внешние ссылки' в Web Viewer и выберете 'Переключить целевое назначение по умолчанию' для Cmd/Ctrl клика, то клик с Cmd/Ctrl будет открывать ссылки внутри Web Viewer.",
        noticeNoWebViewer: "Ядро плагина Web Viewer не обнаружено.",
        noticeFallbackBrowser: "Возврат к открытию в браузере по умолчанию.",
        noticeEnableFirst: "Пожалуйста, сначала включите его в основных плагинах (Core plugins).",
        noticeFailWebViewer: "Не удалось открыть в Web Viewer. Возврат к браузеру по умолчанию.",
        noticeFailWebViewerConsole: "Не удалось открыть в Web Viewer. Проверьте консоль инструментов разработчика для деталей.",
        noticeFailBrowser: "Не удалось открыть браузер по умолчанию. Пожалуйста, проверьте настройки браузера.",
        reuse: "Использовать текущую вкладку Web Viewer (замена URL)",
        "new-tab": "Открыть новую вкладку Web Viewer (без разделения)",
        "new-split": "Открыть в новой разделенной панели Web Viewer",
        browser: "Открыть в браузере по умолчанию"
    },
    ar: {
        title: "Split Web Viewer Modifier",
        intro: "تكوين إجراءات الفتح للنقرات العادية، والنقرات مع Shift، والنقرات مع Cmd/Ctrl. الخيارات موحدة ويمكن دمجها بحرية.",
        langSettingName: "اللغة (Language)",
        langSettingDesc: "اختر لغة العرض لإعدادات الإضافة.",
        clickNormalName: "سلوك النقرة العادية",
        clickNormalDesc: "كيفية فتح الروابط الخارجية عند النقر بشكل عادي (بدون مفاتيح تعديل). يمكنك اتباع إعدادات Web Viewer أو تحديد إجراء صراحة.",
        followSettingOption: "اتباع إعدادات الروابط الخارجية لـ Web Viewer",
        clickShiftName: "سلوك النقرة مع Shift",
        clickShiftDesc: "كيفية فتح الروابط الخارجية عند الضغط على Shift. يوصى بـ 'فتح علامة تبويب Web Viewer جديدة'.",
        clickCmdCtrlName: "سلوك النقرة مع Cmd/Ctrl",
        clickCmdCtrlDesc: "كيفية فتح الروابط الخارجية عند الضغط على Cmd/Ctrl. يوصى بـ 'تبديل الهدف الافتراضي' (Web Viewer <-> المتصفح).",
        toggleDefaultOption: "تبديل الهدف الافتراضي (Web Viewer ↔ المتصفح)",
        disabledOption: "معطل (اتباع النقرة العادية)",
        splitDirectionName: "اتجاه التقسيم",
        splitDirectionDesc: "أين يتم التقسيم. 'vertical' يقسم إلى اليمين، و 'horizontal' يقسم إلى الأسفل. ينطبق فقط عند إنشاء لوحة تقسيم جديدة.",
        splitVertical: "رأسي (تقسيم لليمين)",
        splitHorizontal: "أفقي (تقسيم للأسفل)",
        focusPaneName: "التركيز على التقسيم الجديد بعد الفتح",
        focusPaneDesc: "عند التفعيل، يتم نقل التركيز تلقائيًا إلى لوحة Web Viewer بعد فتح الرابط.",
        fallbackName: "الرجوع إلى المتصفح عند عدم توفر Web Viewer",
        fallbackDesc: "عند إيقاف إضافة Web Viewer الأساسية أو فشلها، يتم فتح الرابط تلقائيًا في متصفح النظام الافتراضي.",
        detectionFallbackName: "سلوك الرجوع عند فشل الكشف التلقائي",
        detectionFallbackDesc: "يستخدم فقط عندما يكون 'سلوك النقرة العادية' مضبوطًا على 'اتباع إعدادات الروابط الخارجية لـ Web Viewer' وتفشل الإضافة في الكشف عن حالة مفتاح التبديل الداخلي لـ Web Viewer.",
        detectBrowserOption: "التعامل كـ 'تعطيل روابط Web Viewer الخارجية' (المتصفح الافتراضي)",
        detectWebViewOption: "التعامل كـ 'تفعيل روابط Web Viewer الخارجية' (استخدام Web Viewer)",
        debugLogName: "سجل التصحيح",
        debugLogDesc: "طباعة سجلات الاعتراض في وحدة تحكم أدوات المطورين. مفيد لاستكشاف أخطاء فتح الروابط وإصلاحها.",
        tipText: "نصيحة: إذا قمت بإيقاف تشغيل خيار 'فتح الروابط الخارجية' في Web Viewer، وضبطت 'سلوك النقرة مع Cmd/Ctrl' هنا على 'تبديل الهدف الافتراضي'، فإن النقرة مع Cmd/Ctrl ستفتح الروابط داخل Web Viewer.",
        noticeNoWebViewer: "لم يتم الكشف عن إضافة Web Viewer الأساسية.",
        noticeFallbackBrowser: "تم الرجوع لفتح الرابط في المتصفح الافتراضي.",
        noticeEnableFirst: "يرجى تفعيلها في الإضافات الأساسية (Core plugins) أولاً.",
        noticeFailWebViewer: "فشل الفتح في Web Viewer. تم الرجوع للمتصفح الافتراضي.",
        noticeFailWebViewerConsole: "فشل الفتح في Web Viewer. تحقق من وحدة تحكم أدوات المطورين للحصول على التفاصيل.",
        noticeFailBrowser: "فشل فتح المتصفح الافتراضي. يرجى التحقق من إعدادات متصفح النظام الافتراضي.",
        reuse: "إعادة استخدام علامة تبويب Web Viewer الحالية (في نفس المكان)",
        "new-tab": "فتح علامة تبويب Web Viewer جديدة (بدون تقسيم)",
        "new-split": "فتح في لوحة Web Viewer مقسمة جديدة",
        browser: "الفتح في متصفح النظام الافتراضي"
    },
    id: {
        title: "Split Web Viewer Modifier",
        intro: "Konfigurasikan aksi buka untuk klik biasa, klik Shift, dan klik Cmd/Ctrl. Opsi disatukan dan dapat dikombinasikan dengan bebas.",
        langSettingName: "Bahasa (Language)",
        langSettingDesc: "Pilih bahasa tampilan untuk pengaturan plugin.",
        clickNormalName: "Perilaku klik biasa",
        clickNormalDesc: "Bagaimana tautan eksternal terbuka ketika diklik secara biasa (tanpa tombol pengubah). Anda dapat mengikuti pengaturan Web Viewer atau menentukan aksi secara eksplisit.",
        followSettingOption: "Ikuti pengaturan tautan eksternal Web Viewer",
        clickShiftName: "Perilaku klik Shift",
        clickShiftDesc: "Bagaimana tautan eksternal terbuka ketika menahan tombol Shift. Disarankan 'Buka tab Web Viewer baru'.",
        clickCmdCtrlName: "Perilaku klik Cmd/Ctrl",
        clickCmdCtrlDesc: "Bagaimana tautan eksternal terbuka ketika menahan tombol Cmd/Ctrl. Disarankan 'Alihkan target default' (Web Viewer <-> Browser).",
        toggleDefaultOption: "Alihkan target default (Web Viewer ↔ Browser)",
        disabledOption: "Dinonaktifkan (Ikuti klik biasa)",
        splitDirectionName: "Arah pemisahan",
        splitDirectionDesc: "Di mana letak pemisahan. 'vertical' memisah ke kanan, 'horizontal' memisah ke bawah. Hanya berlaku ketika panel pemisahan baru dibuat.",
        splitVertical: "vertikal (Pisah ke kanan)",
        splitHorizontal: "horizontal (Pisah ke bawah)",
        focusPaneName: "Fokus pada pemisahan baru setelah dibuka",
        focusPaneDesc: "Saat diaktifkan, otomatis memindahkan fokus ke panel Web Viewer setelah membuka tautan.",
        fallbackName: "Kembali ke browser saat Web Viewer tidak tersedia",
        fallbackDesc: "Ketika plugin inti Web Viewer dinonaktifkan atau gagal, otomatis membuka tautan di browser bawaan sistem.",
        detectionFallbackName: "Perilaku fallback saat deteksi otomatis gagal",
        detectionFallbackDesc: "Hanya digunakan ketika 'Perilaku klik biasa' diatur ke 'Ikuti pengaturan tautan eksternal Web Viewer' dan plugin gagal mendeteksi status sakelar internal Web Viewer.",
        detectBrowserOption: "Anggap sebagai 'Tautan eksternal Web Viewer dinonaktifkan' (Gunakan browser default)",
        detectWebViewOption: "Anggap sebagai 'Tautan eksternal Web Viewer diaktifkan' (Gunakan Web Viewer)",
        debugLogName: "Log debug",
        debugLogDesc: "Cetak log debug ke Developer Tools Console. Berguna untuk mendiagnosis masalah pembukaan tautan.",
        tipText: "Tips: Jika Anda mematikan opsi 'Buka tautan eksternal' pada Web Viewer, dan mengatur 'Perilaku klik Cmd/Ctrl' di sini ke 'Alihkan target default', maka klik Cmd/Ctrl + klik akan membuka tautan di dalam Web Viewer.",
        noticeNoWebViewer: "Plugin inti Web Viewer tidak terdeteksi.",
        noticeFallbackBrowser: "Beralih membuka di browser default.",
        noticeEnableFirst: "Silakan aktifkan terlebih dahulu di Core plugins.",
        noticeFailWebViewer: "Gagal membuka di Web Viewer. Beralih ke browser default.",
        noticeFailWebViewerConsole: "Gagal membuka di Web Viewer. Periksa konsol Developer Tools untuk detail kesalahan.",
        noticeFailBrowser: "Gagal membuka browser default. Silakan periksa pengaturan browser default sistem Anda.",
        reuse: "Gunakan kembali tab Web Viewer saat ini (navigasi di tempat)",
        "new-tab": "Buka tab Web Viewer baru (tanpa pemisahan)",
        "new-split": "Buka di panel pemisahan Web Viewer baru",
        browser: "Buka di browser bawaan"
    }
};

var m = "webviewer",
    y = "webviewer";
var l = require("obsidian");

var d = class extends l.PluginSettingTab {
    constructor(e, t) {
        super(e, t);
        this.plugin = t;
    }
    display() {
        let { containerEl: e } = this;
        e.empty();

        let lang = this.plugin.settings.language || "en";
        let t_translate = (key) => (TRANSLATIONS[lang] || TRANSLATIONS["en"])[key];

        e.createEl("h2", { text: t_translate("title") });
        e.createEl("p", { text: t_translate("intro") });

        new l.Setting(e)
            .setName(t_translate("langSettingName"))
            .setDesc(t_translate("langSettingDesc"))
            .addDropdown(n => {
                n.addOption("en", "English")
                 .addOption("zh", "简体中文")
                 .addOption("ru", "Русский")
                 .addOption("ar", "العربية")
                 .addOption("id", "Bahasa Indonesia")
                 .setValue(this.plugin.settings.language)
                 .onChange(async i => {
                     this.plugin.settings.language = i;
                     await this.plugin.saveSettings();
                     this.display(); // reload settings panel
                 });
            });

        let t = n => {
            n.addOption("reuse", t_translate("reuse"));
            n.addOption("new-tab", t_translate("new-tab"));
            n.addOption("new-split", t_translate("new-split"));
            n.addOption("browser", t_translate("browser"));
        };

        new l.Setting(e)
            .setName(t_translate("clickNormalName"))
            .setDesc(t_translate("clickNormalDesc"))
            .addDropdown(n => {
                n.addOption("follow-setting", t_translate("followSettingOption"));
                t(n);
                n.setValue(this.plugin.settings.defaultAction).onChange(async i => {
                    this.plugin.settings.defaultAction = i;
                    await this.plugin.saveSettings();
                });
            });

        new l.Setting(e)
            .setName(t_translate("clickShiftName"))
            .setDesc(t_translate("clickShiftDesc"))
            .addDropdown(n => {
                t(n);
                n.addOption("disabled", t_translate("disabledOption"));
                n.setValue(this.plugin.settings.shiftAction).onChange(async i => {
                    this.plugin.settings.shiftAction = i;
                    await this.plugin.saveSettings();
                });
            });

        new l.Setting(e)
            .setName(t_translate("clickCmdCtrlName"))
            .setDesc(t_translate("clickCmdCtrlDesc"))
            .addDropdown(n => {
                n.addOption("toggle-default", t_translate("toggleDefaultOption"));
                t(n);
                n.addOption("disabled", t_translate("disabledOption"));
                n.setValue(this.plugin.settings.modifierAction).onChange(async i => {
                    this.plugin.settings.modifierAction = i;
                    await this.plugin.saveSettings();
                });
            });

        new l.Setting(e)
            .setName(t_translate("splitDirectionName"))
            .setDesc(t_translate("splitDirectionDesc"))
            .addDropdown(n => {
                n.addOption("vertical", t_translate("splitVertical"))
                 .addOption("horizontal", t_translate("splitHorizontal"))
                 .setValue(this.plugin.settings.splitDirection).onChange(async i => {
                     this.plugin.settings.splitDirection = i;
                     await this.plugin.saveSettings();
                 });
            });

        new l.Setting(e)
            .setName(t_translate("focusPaneName"))
            .setDesc(t_translate("focusPaneDesc"))
            .addToggle(n => {
                n.setValue(this.plugin.settings.focusPane).onChange(async i => {
                    this.plugin.settings.focusPane = i;
                    await this.plugin.saveSettings();
                });
            });

        new l.Setting(e)
            .setName(t_translate("fallbackName"))
            .setDesc(t_translate("fallbackDesc"))
            .addToggle(n => {
                n.setValue(this.plugin.settings.fallbackToBrowserWhenWebViewerUnavailable).onChange(async i => {
                    this.plugin.settings.fallbackToBrowserWhenWebViewerUnavailable = i;
                    await this.plugin.saveSettings();
                });
            });

        new l.Setting(e)
            .setName(t_translate("detectionFallbackName"))
            .setDesc(t_translate("detectionFallbackDesc"))
            .addDropdown(n => {
                n.addOption("browser", t_translate("detectBrowserOption"))
                 .addOption("webviewer", t_translate("detectWebViewOption"))
                 .setValue(this.plugin.settings.detectionFallback).onChange(async i => {
                     this.plugin.settings.detectionFallback = i;
                     await this.plugin.saveSettings();
                 });
            });

        new l.Setting(e)
            .setName(t_translate("debugLogName"))
            .setDesc(t_translate("debugLogDesc"))
            .addToggle(n => {
                n.setValue(this.plugin.settings.debugLog).onChange(async i => {
                    this.plugin.settings.debugLog = i;
                    await this.plugin.saveSettings();
                });
            });

        e.createEl("p", {
            text: t_translate("tipText"),
            cls: "setting-item-description"
        });
    }
};

var g = class {
    constructor(e) {
        this.plugin = e;
    }
    resolveAction(e) {
        let t = this.resolveBaseAction();
        if (!e) return t;
        if (e.shiftKey) {
            let n = this.resolveModifierAction(this.plugin.settings.shiftAction, t);
            if (n) return n;
        }
        if (this.isCtrlLikePressed(e)) {
            let n = this.resolveModifierAction(this.plugin.settings.modifierAction, t);
            if (n) return n;
        }
        return t;
    }
    resolveModifierAction(e, t) {
        return !e || e === "disabled" ? null : e === "toggle-default" ? this.toggleTarget(t) : this.normalizeOpenMode(e);
    }
    resolveBaseAction() {
        let e = this.plugin.settings.defaultAction;
        return e === "follow-setting" ? this.getCoreExternalLinkAction() : this.normalizeOpenMode(e);
    }
    normalizeOpenMode(e) {
        switch (e) {
            case "browser":
                return { target: "browser", mode: "browser" };
            case "new-tab":
                return { target: "webviewer", mode: "new-tab" };
            case "new-split":
                return { target: "webviewer", mode: "new-split" };
            case "reuse":
            default:
                return { target: "webviewer", mode: "reuse" };
        }
    }
    toggleTarget(e) {
        return e ? e.target === "browser" ? { target: "webviewer", mode: "reuse" } : { target: "browser", mode: "browser" } : { target: "browser", mode: "browser" };
    }
    isCtrlLikePressed(e) {
        return !!(e.metaKey || e.ctrlKey);
    }
    getCoreExternalLinkAction() {
        return this.detectShouldOpenExternalLinksInWebViewer() ? { target: "webviewer", mode: "reuse" } : { target: "browser", mode: "browser" };
    }
    detectShouldOpenExternalLinksInWebViewer() {
        let e = this.getWebViewerInstance();
        if (!e) return this.plugin.settings.detectionFallback === "webviewer";
        let t = this.findKnownExternalLinkFlag(e);
        if (typeof t == "boolean") return t;
        let n = this.findHeuristicExternalLinkFlag(e);
        return typeof n == "boolean" ? n : this.plugin.settings.detectionFallback === "webviewer";
    }
    getWebViewerInstance() {
        let e = this.plugin.app.internalPlugins;
        if (!e) return null;
        if (typeof e.getEnabledPluginById == "function") {
            let t = e.getEnabledPluginById(y);
            if (t) return t;
        }
        if (typeof e.getPluginById == "function") {
            let t = e.getPluginById(y);
            if (t && t.instance) return t.instance;
        }
        return null;
    }
    findKnownExternalLinkFlag(e) {
        let t = ["openExternalLinks", "openExternalLink", "openHyperlinks", "openHyperlink", "shouldOpenExternalLinks", "shouldOpenHyperlinks", "enableExternalLinks", "enableHyperlinks"],
            n = [e, e.options, e.settings, e.data];
        for (let i of n)
            if (!(!i || typeof i != "object")) {
                for (let o of t)
                    if (typeof i[o] == "boolean") return i[o];
            }
        return null;
    }
    findHeuristicExternalLinkFlag(e) {
        let t = new WeakSet,
            n = [e.options, e.settings, e.data, e];
        for (let i of n) {
            let o = this.walkForExternalLinkBoolean(i, t, 0);
            if (typeof o == "boolean") return o;
        }
        return null;
    }
    walkForExternalLinkBoolean(e, t, n) {
        if (!e || typeof e != "object" || t.has(e) || n > 3) return null;
        t.add(e);
        for (let [i, o] of Object.entries(e))
            if (typeof o == "boolean" && this.looksLikeExternalLinkSwitch(i)) return o;
        for (let i of Object.values(e)) {
            let o = this.walkForExternalLinkBoolean(i, t, n + 1);
            if (typeof o == "boolean") return o;
        }
        return null;
    }
    looksLikeExternalLinkSwitch(e) {
        return /(?:open|enable).*(?:external|hyper(?:link)?)/i.test(e) || /(?:external|hyper(?:link)?).*(?:open|enable)/i.test(e);
    }
};

var E = I(require("obsidian"), 1);
var u = require("obsidian");

var w = class {
    constructor(e) {
        this.plugin = e;
    }
    t_translate(key) {
        let lang = this.plugin.settings.language || "en";
        return (TRANSLATIONS[lang] || TRANSLATIONS["en"])[key];
    }
    performAction(e, t) {
        if (e) {
            if (e.target === "browser") {
                this.openInBrowser(t);
                return;
            }
            this.openInWebViewer(t, { mode: e.mode });
        }
    }
    openInBrowser(e) {
        try {
            let t = this.getOriginalOpenExternalHandlers();
            if (t.shellOpenExternal) {
                t.shellOpenExternal(e);
                return;
            }
            if (typeof E.openExternal == "function") {
                E.openExternal(e);
                return;
            }
            if (t.windowOpen) {
                t.windowOpen(e, "_blank");
                return;
            }
            window.open(e, "_blank");
        } catch (t) {
            console.error("[split-web-viewer-modifier] Failed to open in browser", t);
            new u.Notice(this.t_translate("noticeFailBrowser"));
        }
    }
    getOriginalOpenExternalHandlers() {
        let e = null;
        try {
            let n = typeof require == "function" ? require("electron") : null,
                i = n && (n.shell || n.remote && n.remote.shell);
            i && typeof i.openExternal == "function" && (e = i.openExternal.__original ? i.openExternal.__original : i.openExternal.bind(i));
        } catch (n) {}
        let t = null;
        return typeof window.open == "function" && (t = window.open.__original ? window.open.__original.bind(window) : null), { shellOpenExternal: e, windowOpen: t };
    }
    async openInWebViewer(e, t = {}) {
        let n = t.mode || "reuse";
        if (!this.isWebViewerAvailable()) {
            let i = this.t_translate("noticeNoWebViewer");
            if (this.plugin.settings.fallbackToBrowserWhenWebViewerUnavailable) {
                new u.Notice(`${i} ${this.t_translate("noticeFallbackBrowser")}`);
                this.openInBrowser(e);
                return;
            }
            new u.Notice(`${i} ${this.t_translate("noticeEnableFirst")}`);
            return;
        }
        try {
            let i = this.acquireWebViewerLeaf(n);
            if (!i) throw new Error("Could not acquire a web viewer leaf");
            await i.setViewState({ type: m, active: this.plugin.settings.focusPane, state: { url: e, navigate: !0 } });
            n === "reuse" ? this.plugin.lastWebViewerLeaf = i : this.pickReusableLeaf([this.plugin.lastWebViewerLeaf]) || (this.plugin.lastWebViewerLeaf = i);
            this.plugin.settings.focusPane && typeof this.plugin.app.workspace.revealLeaf == "function" && this.plugin.app.workspace.revealLeaf(i);
        } catch (i) {
            if (console.error("[split-web-viewer-modifier] Failed to open in Web Viewer", i), this.plugin.settings.fallbackToBrowserWhenWebViewerUnavailable) {
                new u.Notice(this.t_translate("noticeFailWebViewer"));
                this.openInBrowser(e);
                return;
            }
            new u.Notice(this.t_translate("noticeFailWebViewerConsole"));
        }
    }
    acquireWebViewerLeaf(e = "reuse") {
        let t = this.plugin.app.workspace;
        if (e === "reuse") {
            let n = this.pickReusableLeaf([this.plugin.lastWebViewerLeaf]);
            if (n) return this.plugin.debug("reuse: reusing last web viewer leaf"), n;
            let i = this.getExistingWebViewerLeaves();
            return i.length > 0 ? (this.plugin.debug("reuse: anchor lost, reusing existing web viewer leaf"), this.plugin.lastWebViewerLeaf = i[0] || null, i[0] || null) : (this.plugin.debug("reuse: no web viewer found, creating new split"), t.getLeaf("split", this.plugin.settings.splitDirection));
        }
        if (e === "new-tab") {
            let n = this.pickAnchorLeaf();
            if (n) {
                let i = this.createSiblingTabLeaf(n);
                if (i) return this.plugin.debug("new-tab: opened next to anchor web viewer leaf"), i;
            }
            return this.plugin.debug("new-tab: no anchor, fall back to split"), t.getLeaf("split", this.plugin.settings.splitDirection);
        }
        return this.plugin.debug("new-split: creating new split web viewer leaf"), t.getLeaf("split", this.plugin.settings.splitDirection);
    }
    pickAnchorLeaf() {
        let e = this.pickReusableLeaf([this.plugin.lastWebViewerLeaf]);
        if (e) return e;
        let t = this.getExistingWebViewerLeaves();
        return t.length > 0 && t[0] || null;
    }
    createSiblingTabLeaf(e) {
        var t, n, i;
        if (!e) return null;
        try {
            let o = this.plugin.app.workspace,
                s = e.parent;
            if (typeof o.createLeafInParent == "function" && s) {
                let a = s,
                    c = typeof ((t = a.children) == null ? void 0 : t.indexOf) == "function" ? a.children.indexOf(e) + 1 : -1;
                return o.createLeafInParent(a, c >= 0 ? c : (i = (n = a.children) == null ? void 0 : n.length) != null ? i : 0);
            }
            return o.setActiveLeaf(e, { focus: !1 }), o.getLeaf("tab");
        } catch (o) {
            return console.error("[split-web-viewer-modifier] createSiblingTabLeaf failed", o), null;
        }
    }
    getExistingWebViewerLeaves() {
        try {
            return this.plugin.app.workspace.getLeavesOfType(m) || [];
        } catch (e) {
            return [];
        }
    }
    pickReusableLeaf(e) {
        if (!Array.isArray(e) || e.length === 0) return null;
        let t = this.getExistingWebViewerLeaves(),
            n = new Set(t);
        for (let i of e)
            if (i && n.has(i)) return i;
        return null;
    }
    isWebViewerAvailable() {
        return !!this.plugin.resolver.getWebViewerInstance();
    }
};

function x(r) {
    let e = n => {
            n instanceof MouseEvent && (r.lastPointerEvent = {
                metaKey: n.metaKey,
                ctrlKey: n.ctrlKey,
                shiftKey: n.shiftKey,
                altKey: n.altKey,
                button: n.button,
                timestamp: Date.now()
            });
        },
        t = n => {
            try {
                R(r, n);
            } catch (i) {
                console.error("[split-web-viewer-modifier] mouse handler error", i);
            }
        };
    document.addEventListener("mousedown", e, !0);
    document.addEventListener("mouseup", e, !0);
    document.addEventListener("click", t, !0);
    document.addEventListener("auxclick", t, !0);
    r.register(() => {
        document.removeEventListener("mousedown", e, !0);
        document.removeEventListener("mouseup", e, !0);
        document.removeEventListener("click", t, !0);
        document.removeEventListener("auxclick", t, !0);
    });
}

function R(r, e) {
    if (!(e instanceof MouseEvent) || e.defaultPrevented || e.button !== 0) return;
    let t = B(e.target);
    if (!t) return;
    let n = C(t);
    if (!n) return;
    let i = r.resolver.resolveAction(e);
    i && (r.debug("DOM click intercepted", { url: n, action: i }), e.preventDefault(), e.stopImmediatePropagation(), e.stopPropagation(), r.executor.performAction(i, n));
}

function B(r) {
    return r instanceof HTMLElement ? r.closest("a[href]") : null;
}

function C(r) {
    let e = r.getAttribute("href") || "";
    return v(e);
}

function v(r) {
    if (typeof r != "string" || !r) return null;
    try {
        let e = new URL(r);
        if (e.protocol === "http:" || e.protocol === "https:") return e.toString();
    } catch (e) {
        return null;
    }
    return null;
}

function V(r) {
    let e = r.lastPointerEvent;
    return e && Date.now() - e.timestamp < 1500 ? {
        metaKey: e.metaKey,
        ctrlKey: e.ctrlKey,
        shiftKey: e.shiftKey,
        altKey: e.altKey,
        button: e.button
    } : {
        metaKey: !1,
        ctrlKey: !1,
        shiftKey: !1,
        altKey: !1,
        button: 0
    };
}

function k(r) {
    let e = window.open;
    if (typeof e != "function" || e.__splitWebViewerModifierPatched) return;
    let t = function (n, i, o) {
        try {
            let s = typeof n == "string" ? n : n == null ? void 0 : n.toString(),
                a = v(s || "");
            if (a) {
                let c = V(r),
                    h = r.resolver.resolveAction(c);
                if (h) return r.debug("window.open intercepted", { url: a, action: h }), r.executor.performAction(h, a), null;
            }
        } catch (s) {
            console.error("[split-web-viewer-modifier] window.open patch error", s);
        }
        return e.call(this, n, i, o);
    };
    t.__splitWebViewerModifierPatched = !0;
    t.__original = e;
    window.open = t;
    r.register(() => {
        window.open === t && (window.open = e);
    });
}

function A(r) {
    let e = null;
    try {
        let i = typeof require == "function" ? require("electron") : null;
        e = i && (i.shell || i.remote && i.remote.shell);
    } catch (i) {
        return;
    }
    if (!e || typeof e.openExternal != "function" || e.openExternal.__splitWebViewerModifierPatched) return;
    let t = e.openExternal.bind(e),
        n = function (i, ...o) {
            try {
                let s = v(i);
                if (s) {
                    let a = V(r),
                        c = r.resolver.resolveAction(a);
                    if (c) return r.debug("shell.openExternal intercepted", { url: s, action: c }), c.target === "webviewer" ? (r.executor.performAction(c, s), Promise.resolve()) : t(i, ...o);
                }
            } catch (s) {
                console.error("[split-web-viewer-modifier] shell.openExternal patch error", s);
            }
            return t(i, ...o);
        };
    n.__splitWebViewerModifierPatched = !0;
    n.__original = t;
    e.openExternal = n;
    r.register(() => {
        e.openExternal === n && (e.openExternal = t);
    });
}

var b = class extends S.Plugin {
    constructor() {
        super(...arguments);
        this.lastPointerEvent = null;
        this.lastWebViewerLeaf = null;
    }
    async onload() {
        this.resolver = new g(this);
        this.executor = new w(this);
        await this.loadSettings();
        this.addSettingTab(new d(this.app, this));
        x(this);
        k(this);
        A(this);
    }
    onunload() {}
    async loadSettings() {
        let t = await this.loadData() || {};
        this.migrateSettings(t);
        this.settings = Object.assign({}, L, t);
    }
    migrateSettings(t) {
        if (!t || typeof t != "object") return;
        let n = {
            "follow-webviewer-setting": "follow-setting",
            webviewer: "reuse"
        };
        t.defaultAction && n[t.defaultAction] && (t.defaultAction = n[t.defaultAction]);
        let i = {
            "toggle-default-target": "toggle-default",
            webviewer: "reuse"
        };
        t.modifierAction && i[t.modifierAction] && (t.modifierAction = i[t.modifierAction]);
        let o = {
            "new-tab-webviewer": "new-tab",
            "new-split": "new-split"
        };
        t.shiftAction && o[t.shiftAction] && (t.shiftAction = o[t.shiftAction]);
        t.reusePolicy !== void 0 && delete t.reusePolicy;
    }
    async saveSettings() {
        await this.saveData(this.settings);
    }
    debug(...t) {
        this.settings && this.settings.debugLog && console.log("[split-web-viewer-modifier]", ...t);
    }
};
